### ISSUE TITLE
Writeup and example of _ambiguation_ of dependent name

### ISSUE THREAD

**Issue by BengtGustafsson** [atomgalaxy/isocpp-universal-template-param#14]
A text and example which shows how a dependent name needs ambiguation to be used as an argument for a UTP without being implicitly disambiguated as a value.

Also show that this is NOT required when using a UTP.

**Problem: How do we disambiguate an UTP to be a value?**

**Comment by BengtGustafsson** [comment]
I think this is outdated, if we can agree that ambiguation is never necessary. See issue #

**Comment by camaclean** [comment]
Yes, this is outdated. A UTP is parsed as a value unless it is ambiguated again with `template auto`
