### ISSUE TITLE
Provide example on function template overloading

### ISSUE THREAD

**Issue by mpusz** [atomgalaxy/isocpp-universal-template-param#6]

**Comment by BengtGustafsson** [comment]
This was an example on _function_ template overloading, similar to what I had in the presentation. We already have the example showing how this allows any class template overloading via specialization.


![image](https://user-images.githubusercontent.com/16004348/187776783-05ea9adc-44b7-43a2-b845-7e7a0a7a274d.png)

**Comment by mpusz** [comment]
In such a case I do not have a better example. I think we can use the one from your presentation?

**Comment by BengtGustafsson** [comment]
I guess so. I assume the wording section also needs a formal specification that anyname is less specific than anything else.
